### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by jrsg** [UniversidadCristobalColon/pw2-e3-Arzival#1]
Alinea los _checkboxes_ a la izquierda de sus etiquetas.
https://github.com/UniversidadCristobalColon/pw2-e3-Arzival/blob/bd78c54c53590dbb455811ad46046356c41f25f0/pw2-e5.html#L41

Faltó el atributo `name`
https://github.com/UniversidadCristobalColon/pw2-e3-Arzival/blob/bd78c54c53590dbb455811ad46046356c41f25f0/pw2-e5.html#L52

**Comment by Arzival** [comment]
agregre el atributo name y corregi el orden de los checkbox
